# DigitalOcean App Platform Specification
# Deploy with: doctl apps create --spec .do/app.yaml

name: photo-memory-app

region: nyc

services:
  # Backend API
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/photo-memory-app
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CLERK_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CLERK_PUBLISHABLE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_BUCKET
        scope: RUN_TIME
        value: photo-memory-app
      - key: DO_SPACES_REGION
        scope: RUN_TIME
        value: nyc3
      - key: DO_SPACES_ENDPOINT
        scope: RUN_TIME
        value: https://nyc3.digitaloceanspaces.com
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}

  # Frontend static site
  - name: frontend
    github:
      repo: YOUR_GITHUB_USERNAME/photo-memory-app
      branch: main
      deploy_on_push: true
    source_dir: frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    build_command: npm run build
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${APP_URL}/api
      - key: VITE_CLERK_PUBLISHABLE_KEY
        scope: BUILD_TIME
        type: SECRET

databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1
